package remoter.compiler.kbuilder

import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.toClassName
import com.squareup.kotlinpoet.ksp.toTypeVariableName
import remoter.RemoterProxy
import remoter.RemoterProxyListener
import remoter.RemoterStub

internal class KClassBuilder(
    element: KSClassDeclaration,
    bindingManager: KBindingManager
) : KRemoterBuilder(element, bindingManager) {

    companion object {
        const val PROXY_SUFFIX = "_Proxy"
        const val STUB_SUFFIX = "_Stub"
    }

    private val proxyClassName = remoterInterfaceClassName + PROXY_SUFFIX
    private val stubClassName = remoterInterfaceClassName + STUB_SUFFIX

    private fun interfaceTypeName(): TypeName {
        val classDecl = remoterInterfaceElement
        return if (classDecl.typeParameters.isEmpty()) {
            classDecl.toClassName()
        } else {
            classDecl.toClassName().parameterizedBy(
                classDecl.typeParameters.map { TypeVariableName(it.name.asString()) }
            )
        }
    }

    fun generateProxy(): FileSpec {
        val fileSpecBuilder = FileSpec.builder(remoterInterfacePackageName, proxyClassName)

        val proxyBuilder = TypeSpec.classBuilder(proxyClassName)
            .addKdoc("Wraps a remote [IBinder] that implements [$remoterInterfaceClassName] interface\n")
            .addKdoc("<p/>\n")
            .addKdoc("@param remoteBinder An [IBinder] that exposes a remote [$remoterInterfaceClassName]\n\n")
            .addKdoc("<p/>\n")
            .addKdoc("Autogenerated by <a href=\"https://bit.ly/Remoter\">Remoter</a>\n")
            .addAnnotation(AnnotationSpec.builder(Suppress::class).addMember("\"UNCHECKED_CAST\"").build())
            .addModifiers(KModifier.PUBLIC, KModifier.OPEN)
            .addSuperinterface(RemoterProxy::class.java)
            .addSuperinterface(interfaceTypeName())
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(
                        ParameterSpec.builder("remoteBinder", ClassName("android.os", "IBinder").copy(true)).build()
                    ).build()
            )
            .addProperty(
                PropertySpec.builder("remoteBinder", ClassName("android.os", "IBinder").copy(true))
                    .mutable().addModifiers(KModifier.PRIVATE).initializer("remoteBinder").build()
            )

        bindingManager.getFieldBuilder(remoterInterfaceElement).addProxyFields(proxyBuilder)

        if (bindingManager.hasRemoterBuilder()) {
            proxyBuilder.addFunction(
                FunSpec.constructorBuilder()
                    .addParameter(ParameterSpec.builder("serviceConnector", ClassName("remoter.builder", "IServiceConnector")).build())
                    .addKdoc("Initialize this with a [remoter.builder.IServiceConnector] that connects to service using suspend connect")
                    .addStatement("this._remoterServiceConnector = serviceConnector")
                    .beginControlFlow("serviceConnector.onServiceDisconnect")
                    .addStatement("_serviceInitComplete = kotlinx.coroutines.CompletableDeferred<Boolean>()")
                    .endControlFlow()
                    .beginControlFlow("serviceConnector.onServiceConnect")
                    .addStatement("__initServiceConnection()")
                    .endControlFlow()
                    .callThisConstructor("null")
                    .build()
            )
            proxyBuilder.addFunction(
                FunSpec.constructorBuilder()
                    .addParameter("context", ClassName("android.content", "Context"))
                    .addParameter("serviceIntentAction", String::class)
                    .addParameter(ParameterSpec.builder("flags", Int::class).defaultValue("Context.BIND_AUTO_CREATE").build())
                    .callThisConstructor(CodeBlock.of("%T.of(context, serviceIntentAction, flags)", ClassName("remoter.builder", "ServiceConnector")))
                    .addKdoc(CodeBlock.builder()
                        .add("Creates an instance of this proxy that connects to a service exposed through the given [serviceIntentAction]\n")
                        .add("@param flags Optional flags to use while binding with service. Default use [Context.BIND_AUTO_CREATE]")
                        .build())
                    .build()
            )
            proxyBuilder.addFunction(
                FunSpec.constructorBuilder()
                    .addParameter("context", ClassName("android.content", "Context"))
                    .addParameter("explicitServiceIntent", ClassName("android.content", "Intent"))
                    .addParameter(ParameterSpec.builder("flags", Int::class).defaultValue("Context.BIND_AUTO_CREATE").build())
                    .addKdoc(CodeBlock.builder()
                        .add("Creates an instance of this proxy that connects to a service exposed through the given [explicitServiceIntent]\n")
                        .add("@param flags Optional flags to use while binding with service. Default use [Context.BIND_AUTO_CREATE]")
                        .build())
                    .callThisConstructor("ServiceConnector.of(context, explicitServiceIntent, flags)")
                    .build()
            )
            proxyBuilder.addFunction(
                FunSpec.builder("__initServiceConnection")
                    .addModifiers(KModifier.PRIVATE)
                    .beginControlFlow("_proxyScope.%M", MemberName("kotlinx.coroutines", "launch"))
                    .addStatement("_binderID = __remoter_getStubID_sus()")
                    .addStatement("_stubProcess = __remoter_getStubProcessID_sus()")
                    .addStatement("_serviceInitComplete.complete(true)")
                    .endControlFlow()
                    .build()
            )
        }

        for (typeParam in remoterInterfaceElement.typeParameters) {
            proxyBuilder.addTypeVariable(typeParam.toTypeVariableName())
        }

        proxyBuilder.addType(buildDeathRecipient())
        bindingManager.getFunctionBuilder(remoterInterfaceElement).addProxyMethods(proxyBuilder)
        fileSpecBuilder.addType(proxyBuilder.build())
        return fileSpecBuilder.build()
    }

    fun generateStub(): FileSpec {
        val fileSpecBuilder = FileSpec.builder(remoterInterfacePackageName, stubClassName)

        val stubClassBuilder = TypeSpec.classBuilder(stubClassName)
            .addModifiers(KModifier.PUBLIC, KModifier.OPEN)
            .addSuperinterface(RemoterStub::class.java)
            .addKdoc("Wraps a [$remoterInterfaceClassName] implementation and expose it as a remote [IBinder]\\n")
            .addKdoc("Initialize this [$stubClassName] with the given [$remoterInterfaceClassName] implementation \n\n")
            .addAnnotation(AnnotationSpec.builder(Suppress::class).addMember("\"UNCHECKED_CAST\"").build())
            .superclass(ClassName("android.os", "Binder"))

        for (typeParam in remoterInterfaceElement.typeParameters) {
            stubClassBuilder.addTypeVariable(typeParam.toTypeVariableName())
        }

        stubClassBuilder.addType(getBinderWrapper())

        stubClassBuilder.primaryConstructor(
            FunSpec.constructorBuilder()
                .addParameter(ParameterSpec.builder("serviceImpl", interfaceTypeName().copy(true)).build())
                .build()
        )
        stubClassBuilder.addProperty(
            PropertySpec.builder("serviceImpl", interfaceTypeName().copy(true))
                .mutable().addModifiers(KModifier.PRIVATE).initializer("serviceImpl").build()
        )

        bindingManager.getFieldBuilder(remoterInterfaceElement).addStubFields(stubClassBuilder)
        stubClassBuilder.addInitializerBlock(
            CodeBlock.builder().addStatement("this.attachInterface(binderWrapper, DESCRIPTOR)").build()
        )
        bindingManager.getFunctionBuilder(remoterInterfaceElement).addStubMethods(stubClassBuilder)

        fileSpecBuilder.addType(stubClassBuilder.build())
        return fileSpecBuilder.build()
    }

    private fun buildDeathRecipient() =
        TypeSpec.classBuilder("DeathRecipient")
            .addModifiers(KModifier.PRIVATE)
            .addSuperinterface(ClassName("android.os", "IBinder.DeathRecipient"))
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(ParameterSpec.builder("proxyListener", RemoterProxyListener::class.asTypeName().copy(nullable = true)).build())
                    .build()
            )
            .addProperty(PropertySpec.builder("proxyListener", RemoterProxyListener::class.asTypeName().copy(nullable = true), KModifier.PRIVATE)
                .mutable().initializer("proxyListener").build())
            .addFunction(FunSpec.builder("binderDied").addModifiers(KModifier.OVERRIDE).addCode("proxyListener?.onProxyDead()").build())
            .addFunction(FunSpec.builder("unregister").addModifiers(KModifier.PUBLIC).addCode("proxyListener = null").build())
            .build()

    private fun getBinderWrapper() =
        TypeSpec.classBuilder("BinderWrapper")
            .addModifiers(KModifier.PRIVATE)
            .addProperty(PropertySpec.builder("binder", ClassName("android.os", "IBinder").copy(true))
                .mutable().addModifiers(KModifier.PUBLIC).initializer("binder").build())
            .primaryConstructor(
                FunSpec.constructorBuilder()
                    .addParameter(ParameterSpec.builder("binder", ClassName("android.os", "IBinder").copy(true)).build())
                    .build()
            )
            .addFunction(FunSpec.builder("asBinder")
                .addModifiers(KModifier.PUBLIC, KModifier.OVERRIDE)
                .returns(ClassName("android.os", "IBinder").copy(true))
                .addStatement("return binder")
                .build())
            .addSuperinterface(ClassName("android.os", "IInterface"))
            .build()
}
