/**
 * **Remoter** is an alternative to Android AIDL for Android Remote IPC services using plain interfaces.
 *
 * Example:
 * ```
 * // Remoter annotation marks this interface as a remoter service interface
 * @Remoter
 * interface ISampleService {
 *
 *     // An example where parameters can be in, out or inout
 *     fun foo(a: Boolean,
 *             @ParamIn arrayIn: BooleanArray,
 *             @ParamOut arrayOut: BooleanArray,
 *             arrayInOut: BooleanArray): Boolean
 *
 *     // An example to mark a method as oneway asynchronous method
 *     @Oneway
 *     fun asynchronousFoo(x: Int)
 * }
 * ```
 *
 * At the **client** side — wrap the binder from `ServiceConnection` with the autogenerated Proxy:
 * ```
 * val sampleService: ISampleService = ISampleService_Proxy(binder)
 * ```
 *
 * At the **service** side — wrap the implementation with the autogenerated Stub and return it from your service:
 * ```
 * override fun onBind(intent: Intent): IBinder = ISampleService_Stub(sampleServiceImpl)
 * ```
 *
 * To add Remoter to your project, add these to your Gradle **dependencies**:
 *
 * `api("me.sergeich:remoter-annotations:VERSION")`
 *
 * `ksp("me.sergeich:remoter:VERSION")`
 */
package remoter.annotations
